version: '3'

services:
  expotes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Add `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` to the environment variables
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - PROD_STATIC_PATH=/app/dashboard
      - DATABASE_URL=postgres://postgres:postgres@expotes-db:5432/expotes
      - REDIS_URL=redis://:mypassword@expotes-redis:6379
      - MINIO_ENDPOINT=expotes-minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

    depends_on:
      - expotes-db
      - expotes-minio
      - expotes-redis

  expotes-db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expotes
    ports:
      - '5532:5432'
    volumes:
      - expotes-db:/var/lib/postgresql/data

  expotes-minio:
    image: minio/minio
    ports: 
      - "9100:9000"
      - "9101:9001" 
    volumes:
      - expotes-minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
  
  expotes-redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass mypassword
      
volumes:
  expotes-db:
  expotes-minio-data: